---
name: build-metaprotocol

on: [push, pull_request]

env:
  META_PROTOCOL_PROXY_REPO: meta-protocol-proxy
jobs:
  BuildMetaProtocolBinary:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    strategy:
      fail-fast: true
    name: BuildMetaProtocol
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
         export WORKDIR=`pwd`
         echo $WORKDIR
         git config --global --add safe.directory "$GITHUB_WORKSPACE"
         git config --global --add safe.directory $WORKDIR
         docker run -t --name meta-protocol-proxy-build -v $WORKDIR:/meta-protocol-proxy -w/meta-protocol-proxy  aeraki/meta-protocol-proxy-build:2022-0429-0  sh -c "git config --global --add safe.directory /meta-protocol-proxy && make build"
         ls -lah 
         #ls -lah $WORKDIR/bazel-bin/envoy
